### ISSUE TITLE
BrokenPipeError when using more than one job

### ISSUE THREAD

**Issue by WillKoehrsen** [Featuretools/featuretools#185]
When trying to run `dfs` on a fairly large entityset, whenever `n_jobs` is more than 1, I receive the following error:

"BrokenPipeError: [Errno 32] Broken pipe"

I'm running Red Hat Enterprise Linux Server release 7.3. My machine has 20 cores and 64 total GB of memory. I'm not sure if the issue is with my hardware or with featuretools. 

The complete traceback is below:

```
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 849, in callback
    result_list.append(f.result())
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/deploy/local.py", line 203, in _start_worker
    yield w._start()
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/nanny.py", line 156, in _start
    response = yield self.instantiate()
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/nanny.py", line 224, in instantiate
    self.process.start()
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/nanny.py", line 347, in start
    self.init_result_q = init_q = mp_context.Queue()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/context.py", line 101, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/context.py", line 66, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/synchronize.py", line 163, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/synchronize.py", line 81, in __init__
    register(self._semlock.name)
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/semaphore_tracker.py", line 69, in register
    self._send('REGISTER', name)
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/semaphore_tracker.py", line 82, in _send
    nbytes = os.write(self._fd, msg)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/forkserver.py", line 184, in main
    _serve_one(s, listener, alive_r, handler)
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/forkserver.py", line 218, in _serve_one
    code = spawn._main(child_r)
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/spawn.py", line 115, in _main
    prepare(preparation_data)
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/runpy.py", line 240, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/projects/CSE_MSE_RXF131/hpc-members/wjk68/git/modeling/scripts/featuretools_home_credit_advanced.py", line 237, in <module>
    chunk_size = 1000)
  File "/home/wjk68/.local/lib/python3.5/site-packages/featuretools/synthesis/dfs.py", line 213, in dfs
    verbose=verbose)
  File "/home/wjk68/.local/lib/python3.5/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 239, in calculate_feature_matrix
    dask_kwargs=dask_kwargs or {})
  File "/home/wjk68/.local/lib/python3.5/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 536, in parallel_calculate_chunks
    dask_kwargs=dask_kwargs)
  File "/home/wjk68/.local/lib/python3.5/site-packages/featuretools/computational_backends/utils.py", line 215, in create_client_and_cluster
    **dask_kwargs)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/deploy/local.py", line 136, in __init__
    self.start(ip=ip, n_workers=n_workers)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/deploy/local.py", line 166, in start
    self.sync(self._start, **kwargs)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/deploy/local.py", line 159, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/utils.py", line 275, in sync
    six.reraise(*error[0])
  File "/home/wjk68/.local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/utils.py", line 260, in f
    result[0] = yield make_coro()
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/deploy/local.py", line 186, in _start
    yield [self._start_worker(**self.worker_kwargs) for i in range(n_workers)]
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 849, in callback
    result_list.append(f.result())
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/deploy/local.py", line 203, in _start_worker
    yield w._start()
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/nanny.py", line 156, in _start
    response = yield self.instantiate()
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/nanny.py", line 224, in instantiate
    self.process.start()
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/wjk68/.local/lib/python3.5/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/home/wjk68/.local/lib/python3.5/site-packages/distributed/nanny.py", line 347, in start
    self.init_result_q = init_q = mp_context.Queue()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/context.py", line 101, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/context.py", line 66, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/synchronize.py", line 163, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/synchronize.py", line 81, in __init__
    register(self._semlock.name)
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/semaphore_tracker.py", line 69, in register
    self._send('REGISTER', name)
  File "/usr/local/intel-17/openmpi-2_0_1/python/3.5.1/lib/python3.5/multiprocessing/semaphore_tracker.py", line 82, in _send
    nbytes = os.write(self._fd, msg)
BrokenPipeError: [Errno 32] Broken pipe
```

Sorry to leave you with such a mess! I can provide more system info if needed.

**Comment by kmax12** [comment]
Thanks, we'll look into this and report back.

**Comment by rwedge** [comment]
Hi Will,

Could you provide a list of installed python packages in the environment you are using (pip freeze)?  I'm also curious when during the computation this error occurs.  Could you provide output up until the error occurs as well?

**Comment by WillKoehrsen** [comment]
Before the error occurs, the only output is `Built 3595 features` (or however many features I'm trying to create). The progress bar never shows up. 

I did notice that when saving the `EntitySet` as a pickle file, it is over 5 GB. Each core on the machine I'm using has ~ 3 GB of RAM, so could this be the issue? If I understand correctly, for parallelization, the entire entityset is copied to each core? The problem might be that the individual cores do not have enough memory to hold all the data. This is just speculation but I can try with a smaller dataset and see if the problem persists.

**Comment by rwedge** [comment]
Yes, not having enough memory per core could be causing this issue.  You could try lowering the number of cores used and increasing the memory available to each worker.  The [web interface](https://distributed.readthedocs.io/en/latest/web.html) would probably help you figure how much memory each worker needs.  You would need to install bokeh and add 'diagnostics_port' as an entry in the `dask_kwargs` dictionary.  To set custom memory limits for the workers, add a `memory_limit` entry to `dask_kwargs`.  You could try something like this:
```python
ft.calculate_feature_matrix(
    ...,
    n_jobs=6,
    dask_kwargs={'diagnostics_port': 8787, 'memory_limit': 10e9}
)
```

**Comment by WillKoehrsen** [comment]
Changing the number of jobs from 16 to 2 worked. I'm willing to say this was completely a system issue and not a `featuretools` bug. It might be helpful though to have some indication if a `dfs` call will consume too much memory. Is it possible to check the size of the entityset (using `sys.getsizeof`), the available memory resources, and then provide a warning if the resources will be exceeded?
