### ISSUE TITLE
New in version 0.3.0 - AttributeError: 'functools.partial' object has no attribute '__name__'

### ISSUE THREAD

**Issue by ian-perry-ironnet** [Featuretools/featuretools#237]
### Bug/Feature Request Description
Prior to the upgrade everything was running smoothly.  As soon as I upgraded and ran the same code, I ran into

```Traceback (most recent call last):
  File "/project/path/here/data.py", line 468, in arrayify
    dfs_df = ft.calculate_feature_matrix(self.train_feat_dict['features'], self.es)
  File "/Users/ian.perry/anaconda3/envs/cogsys/lib/python3.6/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 258, in calculate_feature_matrix
    pass_columns=pass_columns)
  File "/Users/ian.perry/anaconda3/envs/cogsys/lib/python3.6/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 520, in linear_calculate_chunks
    backend=backend)
  File "/Users/ian.perry/anaconda3/envs/cogsys/lib/python3.6/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 342, in calculate_chunk
    training_window=window)
  File "/Users/ian.perry/anaconda3/envs/cogsys/lib/python3.6/site-packages/featuretools/computational_backends/utils.py", line 34, in wrapped
    r = method(*args, **kwargs)
  File "/Users/ian.perry/anaconda3/envs/cogsys/lib/python3.6/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 316, in calc_results
    profile=profile)
  File "/Users/ian.perry/anaconda3/envs/cogsys/lib/python3.6/site-packages/featuretools/computational_backends/pandas_backend.py", line 196, in calculate_all_features
    result_frame = handler(group, input_frames)
  File "/Users/ian.perry/anaconda3/envs/cogsys/lib/python3.6/site-packages/featuretools/computational_backends/pandas_backend.py", line 423, in _calculate_agg_features
    funcname = func.__name__
AttributeError: 'functools.partial' object has no attribute '__name__'
```

This article might be related [http://louistiao.me/posts/adding-__name__-and-__doc__-attributes-to-functoolspartial-objects/](http://louistiao.me/posts/adding-__name__-and-__doc__-attributes-to-functoolspartial-objects/)

**Comment by kmax12** [comment]
@ian-perry-ironnet are you loading features that were saved in a previous version of Featuretools?

**Comment by ian-perry-ironnet** [comment]
Ah yes that fixed it, thank you!
