### ISSUE TITLE
Multicore DFS using Featuretools

### ISSUE THREAD

**Issue by sarahmish** [Featuretools/featuretools#289]
I'm trying to calculate my feature matrix using the following code which runs fine but takes a lot of time to generate. 
``` 
feature_matrix, features_defs = ft.dfs(entityset=self.es,
                                       target_entity=self.target,
                                       cutoff_time=self.cutoff,
                                       verbose=True)
```
My issue is that when I add the `n_jobs=-1` parameter to the function, I run into distributed errors like the following.
```
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/distributed/deploy/local.py", line 208, in _start_worker
    yield w._start()
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/distributed/nanny.py", line 157, in _start
    response = yield self.instantiate()
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/distributed/nanny.py", line 226, in instantiate
    self.process.start()
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/distributed/nanny.py", line 370, in start
    yield self.process.start()
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/distributed/process.py", line 35, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Users/sarah/anaconda3/lib/python3.6/site-packages/distributed/process.py", line 184, in _start
    process.start()
  File "/Users/sarah/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/Users/sarah/anaconda3/lib/python3.6/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/Users/sarah/anaconda3/lib/python3.6/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/Users/sarah/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/Users/sarah/anaconda3/lib/python3.6/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/sarah/anaconda3/lib/python3.6/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/Users/sarah/anaconda3/lib/python3.6/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

The multicore problem only persists if I use `cutoff_time`; operating in parallel without it runs smoothly.

**Comment by kmax12** [comment]
we haven't seen this below. @sarahmish are you able to share a reproducible example? 

Feel free to email help@featuretools.com if you have data you don't want public.

**Comment by sarahmish** [comment]
I'm using one of your tutorials https://github.com/Featuretools/predict-appointment-noshow
when I add the `n_jobs` parameter, the deep feature synthesis fails.

**Comment by kmax12** [comment]
@sarahmish we're looking into this. however, I have one quick work around you can try.

Can try you manually creating a dask cluster and passing it into `ft.dfs`? It would look something like

```
from dask.distributed import Client, LocalCluster
cluster = LocalCluster()

# Generate features using the constructed entityset
fm, features = ft.dfs(entityset=es,
                      target_entity='appointments',
                      dask_kwargs={'cluster': cluster.scheduler.address},
                      verbose=True)
```

Let me know if that help

**Comment by sarahmish** [comment]
The same issue persists
