### ISSUE TITLE
pip install fail 

### ISSUE THREAD

**Issue by RylandCapital** [Featuretools/featuretools#30]
Using python 2.7

I tried pip install featuretools. seems to work but then stalls here: 

  ```
Using cached jmespath-0.9.3-py2.py3-none-any.whl
Collecting botocore<1.8.0,>=1.7.0 (from boto3->s3fs==0.1.2->featuretools)
  Using cached botocore-1.7.43-py2.py3-none-any.whl
Requirement already satisfied: locket in c:\users\trader\downloads\winpython-64b
it-2.7.10.3\python-2.7.10.amd64\lib\site-packages (from partd>=0.3.8; extra == "
complete"->dask[complete]==0.15.4->featuretools)
Collecting click>=6.6 (from distributed>=1.16; extra == "complete"->dask[complet
e]==0.15.4->featuretools)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting msgpack-python (from distributed>=1.16; extra == "complete"->dask[com
plete]==0.15.4->featuretools)
  Using cached msgpack_python-0.4.8-cp27-cp27m-win_amd64.whl
Requirement already satisfied: singledispatch; python_version < "3.4" in c:\user
s\trader\downloads\winpython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-package
s (from distributed>=1.16; extra == "complete"->dask[complete]==0.15.4->featuret
ools)
Collecting sortedcontainers (from distributed>=1.16; extra == "complete"->dask[c
omplete]==0.15.4->featuretools)
  Using cached sortedcontainers-1.5.7-py2.py3-none-any.whl
Collecting zict>=0.1.3 (from distributed>=1.16; extra == "complete"->dask[comple
te]==0.15.4->featuretools)
  Using cached zict-0.1.3-py2.py3-none-any.whl
Requirement already satisfied: psutil in c:\users\trader\downloads\winpython-64b
it-2.7.10.3\python-2.7.10.amd64\lib\site-packages (from distributed>=1.16; extra
 == "complete"->dask[complete]==0.15.4->featuretools)
Collecting futures; python_version < "3.0" (from distributed>=1.16; extra == "co
mplete"->dask[complete]==0.15.4->featuretools)
  Using cached futures-3.1.1-py2-none-any.whl
Collecting tblib (from distributed>=1.16; extra == "complete"->dask[complete]==0
.15.4->featuretools)
  Using cached tblib-1.3.2-py2.py3-none-any.whl
Collecting tornado>=4.5.1 (from distributed>=1.16; extra == "complete"->dask[com
plete]==0.15.4->featuretools)
Requirement already satisfied: docutils>=0.10 in c:\users\trader\downloads\winpy
thon-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages (from botocore<1.8.0,>
=1.7.0->boto3->s3fs==0.1.2->featuretools)
Collecting heapdict (from zict>=0.1.3->distributed>=1.16; extra == "complete"->d
ask[complete]==0.15.4->featuretools)
Requirement already satisfied: backports-abc>=0.4 in c:\users\trader\downloads\w
inpython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages (from tornado>=4.5
.1->distributed>=1.16; extra == "complete"->dask[complete]==0.15.4->featuretools
)
Requirement already satisfied: certifi in c:\users\trader\downloads\winpython-64
bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages (from tornado>=4.5.1->distrib
uted>=1.16; extra == "complete"->dask[complete]==0.15.4->featuretools)
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.
3\python-2.7.10.amd64\python.exe -u -c "import setuptools, tokenize;__file__='c:
\\users\\trader\\appdata\\local\\temp\\pip-build-kq6znx\\scipy\\setup.py';f=geta
ttr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clos
e();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\trader\appdat
a\local\temp\tmp1dnodvpip-wheel- --python-tag cp27:
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['C:\\Users\\Trader\\Downloads\\WinPython-64bi
t-2.7.10.3\\python-2.7.10.amd64\\lib', 'C:\\', 'C:\\Users\\Trader\\Downloads\\Wi
nPython-64bit-2.7.10.3\\python-2.7.10.amd64\\libs']
    NOT AVAILABLE

  openblas_lapack_info:
  C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\sit
e-packages\numpy\distutils\system_info.py:655: UserWarning: Specified path c:\op
t\64\lib is invalid.
    return self.get_paths(self.section, key)
    libraries libopenblas_v0.2.20_mingwpy not found in []
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas,tatlas not found in C:\Users\Trader\Downloads\WinPython-64b
it-2.7.10.3\python-2.7.10.amd64\lib
    libraries lapack_atlas not found in C:\Users\Trader\Downloads\WinPython-64bi
t-2.7.10.3\python-2.7.10.amd64\lib
    libraries tatlas,tatlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries tatlas,tatlas not found in C:\Users\Trader\Downloads\WinPython-64b
it-2.7.10.3\python-2.7.10.amd64\libs
    libraries lapack_atlas not found in C:\Users\Trader\Downloads\WinPython-64bi
t-2.7.10.3\python-2.7.10.amd64\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries satlas,satlas not found in C:\Users\Trader\Downloads\WinPython-64b
it-2.7.10.3\python-2.7.10.amd64\lib
    libraries lapack_atlas not found in C:\Users\Trader\Downloads\WinPython-64bi
t-2.7.10.3\python-2.7.10.amd64\lib
    libraries satlas,satlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries satlas,satlas not found in C:\Users\Trader\Downloads\WinPython-64b
it-2.7.10.3\python-2.7.10.amd64\libs
    libraries lapack_atlas not found in C:\Users\Trader\Downloads\WinPython-64bi
t-2.7.10.3\python-2.7.10.amd64\libs
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\Trader\Downloads\Win
Python-64bit-2.7.10.3\python-2.7.10.amd64\lib
    libraries lapack_atlas not found in C:\Users\Trader\Downloads\WinPython-64bi
t-2.7.10.3\python-2.7.10.amd64\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\Trader\Downloads\Win
Python-64bit-2.7.10.3\python-2.7.10.amd64\libs
    libraries lapack_atlas not found in C:\Users\Trader\Downloads\WinPython-64bi
t-2.7.10.3\python-2.7.10.amd64\libs
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries f77blas,cblas,atlas not found in C:\Users\Trader\Downloads\WinPyth
on-64bit-2.7.10.3\python-2.7.10.amd64\lib
    libraries lapack_atlas not found in C:\Users\Trader\Downloads\WinPython-64bi
t-2.7.10.3\python-2.7.10.amd64\lib
    libraries f77blas,cblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries f77blas,cblas,atlas not found in C:\Users\Trader\Downloads\WinPyth
on-64bit-2.7.10.3\python-2.7.10.amd64\libs
    libraries lapack_atlas not found in C:\Users\Trader\Downloads\WinPython-64bi
t-2.7.10.3\python-2.7.10.amd64\libs
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\sit
e-packages\numpy\distutils\system_info.py:572: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
    libraries lapack not found in ['C:\\Users\\Trader\\Downloads\\WinPython-64bi
t-2.7.10.3\\python-2.7.10.amd64\\lib', 'C:\\', 'C:\\Users\\Trader\\Downloads\\Wi
nPython-64bit-2.7.10.3\\python-2.7.10.amd64\\libs']
    NOT AVAILABLE

  C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\sit
e-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\sit
e-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  Running from scipy source directory.
  non-existing path in 'scipy\\integrate': 'quadpack.h'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\trader\appdata\local\temp\pip-build-kq6znx\scipy\setup.py", l
ine 416, in <module>
      setup_package()
    File "c:\users\trader\appdata\local\temp\pip-build-kq6znx\scipy\setup.py", l
ine 412, in setup_package
      setup(**metadata)
    File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64
\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "c:\users\trader\appdata\local\temp\pip-build-kq6znx\scipy\setup.py", l
ine 336, in configuration
      config.add_subpackage('scipy')
    File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64
\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
      caller_level = 2)
    File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64
\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
      caller_level = caller_level + 1)
    File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64
\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuratio
n_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64
\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
      caller_level = 2)
    File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64
\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
      caller_level = caller_level + 1)
    File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64
\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuratio
n_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Complete output from command C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.
3\python-2.7.10.amd64\python.exe -u -c "import setuptools, tokenize;__file__='c:
\\users\\trader\\appdata\\local\\temp\\pip-build-kq6znx\\scipy\\setup.py';f=geta
ttr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clos
e();exec(compile(code, __file__, 'exec'))" clean --all:

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).


  ----------------------------------------
  Failed cleaning build dir for scipy
Failed to build scipy
Installing collected packages: tqdm, futures, jmespath, botocore, s3transfer, bo
to3, s3fs, partd, click, msgpack-python, sortedcontainers, heapdict, zict, tblib
, tornado, distributed, dask, scipy, featuretools
  Found existing installation: partd 0.3.2
    Uninstalling partd-0.3.2:
      Successfully uninstalled partd-0.3.2
  Found existing installation: click 5.0
    Uninstalling click-5.0:
      Successfully uninstalled click-5.0
  Found existing installation: tornado 4.2.1
    Uninstalling tornado-4.2.1:
      Successfully uninstalled tornado-4.2.1
Exception:
Traceback (most recent call last):
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\site-packages\pip\req\req_set.py", line 795, in install
    requirement.commit_uninstall()
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\site-packages\pip\req\req_install.py", line 767, in commit_uninstall
    self.uninstalled.commit()
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\site-packages\pip\req\req_uninstall.py", line 142, in commit
    rmtree(self.save_dir)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Users\Trader\Downloads\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\l
ib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
WindowsError: [Error 5] Access is denied: 'c:\\users\\trader\\appdata\\local\\te
mp\\pip-4kia5z-uninstall\\users\\trader\\downloads\\winpython-64bit-2.7.10.3\\py
thon-2.7.10.amd64\\lib\\site-packages\\tornado\\speedups.pyd'
```
tried installing dependecies manually but couldnt make it happen. I need this to work. 
Any help would be awesome!

thanks guys and gals

**Comment by kmax12** [comment]
This looks like an issue installing the scipy dependency on Windows. 

Made a fix in #31. Can you try installing via this command?
```
pip install git+https://github.com/featuretools/featuretools.git@scipy-update
```

**Comment by RylandCapital** [comment]
max coming through in the clutch!

worked immediately.

**Comment by kmax12** [comment]
Thanks! Glad it worked. Closing issue for now
