### ISSUE TITLE
Problem installing featuretools 0.5.1 using Python 2.7

### ISSUE THREAD

**Issue by bukosabino** [Featuretools/featuretools#355]
### Bug

I can not install Featuretools 0.5.1 on python2.7 environment.

Steps to reproduce:

```
> virtualenv -p python2.7 env
> source env/bin/activate
> pip install featuretools==0.5.1
```

More information:

* You can install this packet on Python3.6 without errors.
* You can install featuretools==0.5.0 on Python2.7 without erros.

**Comment by kmax12** [comment]
@bukosabino i am not able to reproduce. what is the error you are getting?

also, what operating system are you running?

**Comment by bukosabino** [comment]
Error:
```
(env) Lecrins-MacBook-Air:~ lecrintech$ pip install --no-cache-dir featuretools==0.5.1
Collecting featuretools==0.5.1
  Downloading https://files.pythonhosted.org/packages/d7/83/d2a5e872a11576ca6ac1899bf69d77132b8f196d3245dc4e7e4a1d2a4a5a/featuretools-0.5.1.tar.gz (150kB)
    100% |████████████████████████████████| 153kB 967kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hz/xjrqrvnd221f17w9cg8rsz580000gn/T/pip-install-3WHRwM/featuretools/setup.py", line 53, in <module>
        long_description_content_type='text/markdown'
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/lecrintech/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/lecrintech/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "/Users/lecrintech/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1075, in obtain
        return installer(requirement)
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
        not self.always_copy, self.local_index
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/package_index.py", line 654, in fetch_distribution
        self.find_packages(requirement)
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/package_index.py", line 487, in find_packages
        self.scan_url(self.index_url + requirement.unsafe_name + '/')
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/package_index.py", line 827, in scan_url
        self.process_url(url, True)
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/package_index.py", line 348, in process_url
        f = self.open_url(url, tmpl % url)
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/package_index.py", line 766, in open_url
        return open_with_auth(url, self.opener)
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/package_index.py", line 961, in _socket_timeout
        return func(*args, **kwargs)
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/package_index.py", line 1063, in open_with_auth
        cred = PyPIConfig().find_credential(url)
      File "/Users/lecrintech/env/lib/python2.7/site-packages/setuptools/package_index.py", line 1019, in __init__
        self.read(rc)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 305, in read
        self._read(fp, filename)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 546, in _read
        raise e
    ConfigParser.ParsingError: File contains parsing errors: /Users/lecrintech/.pypirc
    	[line  2]: '    index-servers =\n'
    	[line  3]: '        pypi\n'
    	[line  5]: '    [pypi]\n'
    	[line  6]: '    repository: https://pypi.python.org/pypi\n'
    	[line  7]: '    username: bukosabino\n'
    	[line  8]: '    password: *************'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hz/xjrqrvnd221f17w9cg8rsz580000gn/T/pip-install-3WHRwM/featuretools/
```

OS: 
```
(env) Lecrins-MacBook-Air:~ lecrintech$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
```

**Comment by kmax12** [comment]
This issue seems to be with your .pypirc file. If you fix that parsing error / delete the file does that fix?
