### ISSUE TITLE
IndexError: Too many levels. when using "time_since_last" and cutoff

### ISSUE THREAD

**Issue by pabloazurduy** [Featuretools/featuretools#363]
failed code 
```
import featuretools as ft


data = ft.demo.load_mock_customer()
# unpack data
customers_df = data["customers"]
sessions_df = data["sessions"]
transactions_df = data["transactions"].merge(data["sessions"]).merge(data["customers"])
products_df = data["products"]

es = ft.EntitySet(id = 'es')
es = es.entity_from_dataframe(entity_id= "transactions",
                              dataframe=transactions_df,
                              index="transaction_id",
                              # parameter tells Featuretools when the data was created.
                              time_index="transaction_time", 
                              # “product_id” should be interpreted as a Categorical variable 
                              # because is an index var 
                              variable_types={"product_id": ft.variable_types.Categorical}
                              )

es = es.entity_from_dataframe(entity_id="products",
                              dataframe=products_df,
                              index="product_id")

new_relationship = ft.Relationship(es["products"]["product_id"],
                                    es["transactions"]["product_id"])
 
es = es.add_relationship(new_relationship)


es = es.normalize_entity(base_entity_id="transactions",
                         new_entity_id="sessions",
                         index="session_id",                         
                         make_time_index="session_start",
                         additional_variables=["device", 
                                               "customer_id", 
                                               "zip_code", 
                                               "session_start", 
                                               "join_date"])

es = es.normalize_entity(base_entity_id="sessions",
                         new_entity_id="customers",
                         index="customer_id",
                         make_time_index="join_date",
                         additional_variables=["zip_code", "join_date"])



import pandas as pd
ct = pd.DataFrame()
ct['customer_id'] = [1, 2, 3]
ct['time'] = pd.to_datetime(['2014-1-1 04:00',
                             '2019-1-1 04:00',
                             '2010-1-1 00:00'])
ct['label'] = [True, True, False]

temporal_cutoffs = ft.make_temporal_cutoffs(ct['customer_id'],
                                            ct['time'],
                                            window_size='1d',
                                            num_windows=100)


fm, features = ft.dfs(entityset=es,
                      target_entity='customers',
                      agg_primitives=[#"avg_time_between",
                                      "time_since_last"
                                      ],

                      cutoff_time=temporal_cutoffs,
                      cutoff_time_in_index=True
                      )
```
Traceback
```
Traceback (most recent call last):

  File "<ipython-input-15-40d3ea266f97>", line 8, in <module>
    cutoff_time_in_index=True

  File "C:\Anaconda3\envs\mantto\lib\site-packages\featuretools\synthesis\dfs.py", line 200, in dfs
    verbose=verbose)

  File "C:\Anaconda3\envs\mantto\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 258, in calculate_feature_matrix
    pass_columns=pass_columns)

  File "C:\Anaconda3\envs\mantto\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 520, in linear_calculate_chunks
    backend=backend)

  File "C:\Anaconda3\envs\mantto\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 342, in calculate_chunk
    training_window=window)

  File "C:\Anaconda3\envs\mantto\lib\site-packages\featuretools\computational_backends\utils.py", line 34, in wrapped
    r = method(*args, **kwargs)

  File "C:\Anaconda3\envs\mantto\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 316, in calc_results
    profile=profile)

  File "C:\Anaconda3\envs\mantto\lib\site-packages\featuretools\computational_backends\pandas_backend.py", line 196, in calculate_all_features
    result_frame = handler(group, input_frames)

  File "C:\Anaconda3\envs\mantto\lib\site-packages\featuretools\computational_backends\pandas_backend.py", line 442, in _calculate_agg_features
    to_merge.reset_index(1, drop=True, inplace=True)

  File "C:\Anaconda3\envs\mantto\lib\site-packages\pandas\core\frame.py", line 4101, in reset_index
    level = [self.index._get_level_number(lev) for lev in level]

  File "C:\Anaconda3\envs\mantto\lib\site-packages\pandas\core\frame.py", line 4101, in <listcomp>
    level = [self.index._get_level_number(lev) for lev in level]

  File "C:\Anaconda3\envs\mantto\lib\site-packages\pandas\core\indexes\base.py", line 1961, in _get_level_number
    self._validate_index_level(level)

  File "C:\Anaconda3\envs\mantto\lib\site-packages\pandas\core\indexes\base.py", line 1955, in _validate_index_level
    (level + 1))

IndexError: Too many levels: Index has only 1 level, not 2


```

**Comment by kmax12** [comment]
@pabloazurduy which version of Featuretools are you running? this works for my in v0.5.1? 

```
import featuretools
print(featuretools.__version__)
```

**Comment by pabloazurduy** [comment]
Thanks @kmax12 I was using `featuretools 0.3.0` updating to `v0.5.1` solved the issue.
