### ISSUE TITLE
Loading previously saved features: ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by nutle** [Featuretools/featuretools#500]
Not sure whether this is a bug or I am doing something incorrectly, but:

assume the feature matrix is created as in all of the example documentation:

```
feature_matrix, feature_defs = ft.dfs(entityset = es,
                                      target_entity = "test",
                                      agg_primitives = ["mean","min","median"],
                                      verbose = True,
                                      n_jobs = 1,
                                      max_depth = 2)
```

this is working fine and I am able to save and export these features without any problems.

However, if we want to move this into production the following workflow breaks:

1. Storing created features:
```
feature_matrix_enc, features_enc = ft.encode_features(feature_matrix, feature_defs)
```
2. Creating file for the export:
```
ft.save_features(features_enc, "feature_definitions")
```
3. Loading the features (for the test case - nothing _actually_ changes, same live environment):
```
saved_features = ft.load_features("feature_definitions")
```
4. Transforming them back, using the same entity ``es`` that was used to create the features:
```
feature_matrix = ft.calculate_feature_matrix(saved_features, es)
```
However, the last step returns the following error:

```
...

  File "pandas\_libs\lib.pyx", line 456, in pandas._libs.lib.astype_intsafe

  File "pandas/_libs/src\util.pxd", line 142, in util.set_value_at_unsafe

ValueError: cannot convert float NaN to integer
```

Is there a way to fix this? If the original feature matrix was created despite those NaN values, can we ignore them on load? Or am I missing something?

Big thanks!

**Comment by kmax12** [comment]
@nutle can you provide the full stack trace? 

also, what version of featuretools are you using?

**Comment by nutle** [comment]
Yes, sorry, full stack:

```
Traceback (most recent call last):

  File "<ipython-input-169-d366d9917a97>", line 7, in <module>
    feature_matrix = ft.calculate_feature_matrix(saved_features, es)

  File "C:\user_dir\\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 267, in calculate_feature_matrix
    pass_columns=pass_columns)

  File "C:\user_dir\\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 530, in linear_calculate_chunks
    backend=backend)

  File "C:\user_dir\\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 351, in calculate_chunk
    training_window=window)

  File "C:\user_dir\\Anaconda3\lib\site-packages\featuretools\computational_backends\utils.py", line 36, in wrapped
    r = method(*args, **kwargs)

  File "C:\user_dir\\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 325, in calc_results
    profile=profile)

  File "C:\user_dir\\Anaconda3\lib\site-packages\featuretools\computational_backends\pandas_backend.py", line 197, in calculate_all_features
    result_frame = handler(group, input_frames)

  File "C:\user_dir\\Anaconda3\lib\site-packages\featuretools\computational_backends\pandas_backend.py", line 323, in _calculate_transform_features
    values = feature_func(*variable_data)

  File "C:\user_dir\\Anaconda3\lib\site-packages\featuretools\primitives\standard\binary_transform.py", line 161, in equal_scalar
    return pd.Series(vals).astype(pd.Series([self.value]).dtype) == self.value

  File "C:\user_dir\\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)

  File "C:\user_dir\\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5001, in astype
    **kwargs)

  File "C:\user_dir\\Anaconda3\lib\site-packages\pandas\core\internals.py", line 3714, in astype
    return self.apply('astype', dtype=dtype, **kwargs)

  File "C:\user_dir\\Anaconda3\lib\site-packages\pandas\core\internals.py", line 3581, in apply
    applied = getattr(b, f)(**kwargs)

  File "C:\user_dir\\Anaconda3\lib\site-packages\pandas\core\internals.py", line 575, in astype
    **kwargs)

  File "C:\user_dir\\Anaconda3\lib\site-packages\pandas\core\internals.py", line 664, in _astype
    values = astype_nansafe(values.ravel(), dtype, copy=True)

  File "C:\user_dir\\Anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 709, in astype_nansafe
    return lib.astype_intsafe(arr.ravel(), dtype).reshape(arr.shape)

  File "pandas\_libs\lib.pyx", line 456, in pandas._libs.lib.astype_intsafe

  File "pandas/_libs/src\util.pxd", line 142, in util.set_value_at_unsafe

ValueError: cannot convert float NaN to integer
```

Workflow is running through Windows 10 + Anaconda + Python 3.7
```
print(ft.__version__)
0.7.0
```

I admit that the original data was not clean, and in time we will clean it and remove the NaN's and the likes if that is going to be necessary.

However, the main concern was that if the original flow was able to handle the data, in theory so should the stored and re-loaded flow, right?

**Comment by kmax12** [comment]
you're right. this is likely a bug. we are trying to reproduce now. are you able to share the data and exact code you ran to hit it? if you prefer you can send it to us directly at help@featuretools.com

**Comment by kmax12** [comment]
@nutle we just implemented a fix in #504. Can you try to install that branch directly and see if the error still persists? 

You can install the branch with this command 
```
pip install -e git://github.com/featuretools/featuretools.git@remove-casting#egg=featuretools
```

**Comment by nutle** [comment]
Thank you for the prompt fix! Will test and get back to you ASAP.

**Comment by nutle** [comment]
Now, after updating the package, the stack is:

```
C:\user_dir\Anaconda3\lib\site-packages\pandas\core\ops.py:1167: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)
Traceback (most recent call last):

  File "<ipython-input-4-d366d9917a97>", line 7, in <module>
    feature_matrix = ft.calculate_feature_matrix(saved_features, es)

  File "C:\user_dir\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 267, in calculate_feature_matrix
    pass_columns=pass_columns)

  File "C:\user_dir\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 530, in linear_calculate_chunks
    backend=backend)

  File "C:\user_dir\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 351, in calculate_chunk
    training_window=window)

  File "C:\user_dir\Anaconda3\lib\site-packages\featuretools\computational_backends\utils.py", line 36, in wrapped
    r = method(*args, **kwargs)

  File "C:\user_dir\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 325, in calc_results
    profile=profile)

  File "C:\user_dir\Anaconda3\lib\site-packages\featuretools\computational_backends\pandas_backend.py", line 197, in calculate_all_features
    result_frame = handler(group, input_frames)

  File "C:\user_dir\Anaconda3\lib\site-packages\featuretools\computational_backends\pandas_backend.py", line 323, in _calculate_transform_features
    values = feature_func(*variable_data)

  File "C:\user_dir\Anaconda3\lib\site-packages\featuretools\primitives\standard\binary_transform.py", line 160, in equal_scalar
    return pd.Series(vals) == self.value

  File "C:\user_dir\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)

  File "C:\user_dir\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1169, in na_op
    raise TypeError("invalid type comparison")

TypeError: invalid type comparison
```

**Comment by kmax12** [comment]
are you able to share a data sample that reproduces the error?

**Comment by kmax12** [comment]
@nutle actually, what version of pandas are you using? I suspect it is below 0.24.0. If so, can you try to upgrade and run the branch again?

**Comment by nutle** [comment]
Sorry for not responding earlier, had a lot of unrelated tasks. I didn't have time earlier to catch the precise row that was causing the bug, but what Ive noticed is that it definitelly crashes when Last and Num-unique are used as primitives. Probably it has something to do with counting nulls?

Pandas should be the latest version, if I recall correctly, since I tested this on a fresh python install.

**Comment by kmax12** [comment]
can you confirm the pandas version?

**Comment by nutle** [comment]
It was in fact 0.23.4, and upgrading to 0.24.2 seems to have solved it. Thank you!
