### ISSUE TITLE
Entity 0 does not exist while the entity id 0 is not seen anywhere

### ISSUE THREAD

**Issue by CHOcho-quan** [Featuretools/featuretools#555]
Entityset: stock
  Entities:
    askvolumes [Rows: 452730, Columns: 6]
    bidvolumes [Rows: 452730, Columns: 6]
    askprices [Rows: 452730, Columns: 6]
    bidprices [Rows: 452730, Columns: 6]
    prices [Rows: 452730, Columns: 9]
  Relationships:
    askvolumes.stock_id -> askprices.stock_id
    bidvolumes.stock_id -> bidprices.stock_id

**Comment by CHOcho-quan** [comment]
Traceback (most recent call last):
  File "featureGeneration.py", line 374, in <module>
    generate_by_ft(10, 30, 30)
  File "featureGeneration.py", line 364, in generate_by_ft
    features, feature_names = ft.dfs(es, 'prices')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/featuretools/utils/entry_point.py", line 46, in function_wrapper
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/featuretools/utils/entry_point.py", line 38, in function_wrapper
    return_value = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/featuretools/synthesis/dfs.py", line 181, in dfs
    entityset = EntitySet("dfs", entities, relationships)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/featuretools/entityset/entityset.py", line 73, in __init__
    for entity in entities:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/featuretools/entityset/entityset.py", line 129, in __getitem__
    raise KeyError('Entity %s does not exist in %s' % (entity_id, self.id))
KeyError: 'Entity 0 does not exist in stock'

**Comment by CHOcho-quan** [comment]
So where is the entity 0 should be ? I haven't seen the entity id anywhere in my program

**Comment by CHOcho-quan** [comment]
Well, it seems that when I run your demo about customers on your website, it still shows me that error. Maybe something goes wrong with your package

**Comment by CHOcho-quan** [comment]
I solved the question by re-installing version 0.6.0

**Comment by CHOcho-quan** [comment]
Well, when I change the version to 0.6.0, the demo runs well but my program is still with that KeyError

**Comment by kmax12** [comment]
@CHOcho-quan can you paste the code of the demo you are running that doesn't work?

also, looking at your stacktrace, you may be calling `ft.dfs` incorrectly.  can you try calling it with the arguments named like this? 

```ft.dfs(entityset=es, target_entity='prices')```

**Comment by CHOcho-quan** [comment]
> @CHOcho-quan can you paste the code of the demo you are running that doesn't work?
> 
> also, looking at your stacktrace, you may be calling `ft.dfs` incorrectly. can you try calling it with the arguments named like this?
> 
> `ft.dfs(entityset=es, target_entity='prices')`

Thank u so much. Solved by adding the argument names. The demo I run is also the same problem, solved by adding the argument names
