### ISSUE TITLE
Error running DFS after filtering feature definitions 

### ISSUE THREAD

**Issue by jonimatix** [Featuretools/featuretools#657]
Hello,

I am using the below code to filter out some features that i want to exclude when running DFS:

features_to_keep = []

for x in features:
    if 'Index' not in x.get_name():
        features_to_keep.append(x)
       
ft.save_features(features_to_keep, 'feature_definitions.json')

However, when i use the filtered feature definitions (features_to_keep) in DFS, I get the following error: 
'list' object has no attribute 'name'

    feature_matrix = ft.calculate_feature_matrix(features_to_keep, 
                                                 entityset = es, 
                                                 n_jobs = 1, 
                                                 verbose = 0,
                                                 chunk_size = 1000)

Can you please have a look and let me know any solution please?

Thanks

**Comment by kmax12** [comment]
@jonimatix can you please share the full stacktrace?

**Comment by jonimatix** [comment]
@kmax12 

There you go:


```
Traceback (most recent call last):

  File "<ipython-input-88-e751d3c08f15>", line 5, in <module>
    chunk_size = 1000)

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 267, in calculate_feature_matrix
    pass_columns=pass_columns)

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 498, in linear_calculate_chunks
    target_time, pass_columns)

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 343, in calculate_chunk
    training_window=window)

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\computational_backends\utils.py", line 37, in wrapped
    r = method(*args, **kwargs)

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 318, in calc_results
    matrix = calculator.run(ids)

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py", line 103, in run
    filter_values=instance_ids)

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py", line 249, in _calculate_features_for_entity
    parent_data=parent_data)

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py", line 280, in _calculate_features_for_entity
    df = self._calculate_features(df, df_trie, not_full_entity_features)

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py", line 290, in _calculate_features
    feature_groups = self.feature_set.group_features(features)

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\computational_backends\feature_set.py", line 111, in group_features
    sort_feats = sorted(features, key=key_func)

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\computational_backends\feature_set.py", line 102, in key_func
    f.relationship_path_name(),

  File "C:\Users\Jonathan\Anaconda3\lib\site-packages\featuretools\feature_base\feature_base.py", line 621, in relationship_path_name
    return self.relationship_path.name

AttributeError: 'list' object has no attribute 'name'
```

This is the code used:

```
features_to_keep = []

for x in features:
    if 'Index' not in x.get_name():
        features_to_keep.append(x)

ft.save_features(features_to_keep, path + "test.json")
f = ft.load_features(path + "test.json")
feature_matrix = ft.calculate_feature_matrix(f, 
                                             entityset = es, 
                                             n_jobs = 1, 
                                             verbose = 0,
                                             chunk_size = 1000)
```

The error seems to feature when you save the feature matrix, loading it again, and using it in dfs

Thanks

**Comment by CJStadler** [comment]
Thanks for reporting @jonimatix! This is now fixed on the master branch, which you can install with

```
pip install --upgrade https://github.com/featuretools/featuretools/zipball/master
```

The next official release will probably be in a few weeks.

**Comment by jonimatix** [comment]
Welcome and thanks for the fix!
