### ISSUE TITLE
featuretools on pyspark occurs "PicklingError: Could not serialize object: TypeError: can't pickle _thread.lock objects"

### ISSUE THREAD

**Issue by lvjiujin** [Featuretools/featuretools#724]
### Bug/Feature Request details 
when I run the featuretools on the spark clusters, "4._feature_Engineering_on_Spark",  it occurs the following errors:

```
Traceback (most recent call last):
  File "/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 235, in dump
    return Pickler.dump(self, obj)
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 378, in save_function
    self.save_function_tuple(obj)
  File "/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 529, in save_function_tuple
    save(closure_values)
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 781, in save_list
    self._batch_appends(obj)
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 808, in _batch_appends
    save(tmp[0])
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 372, in save_function
    self.save_function_tuple(obj)
  File "/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 525, in save_function_tuple
    save(f_globals)
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 372, in save_function
    self.save_function_tuple(obj)
  File "/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 525, in save_function_tuple
    save(f_globals)
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 804, in save_reduce
    save(state)
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/data/anaconda/envs/py36/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.lock objects
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py in dump(self, obj)
    234         try:
--> 235             return Pickler.dump(self, obj)
    236         except RuntimeError as e:

/data/anaconda/envs/py36/lib/python3.6/pickle.py in dump(self, obj)
    408             self.framer.start_framing()
--> 409         self.save(obj)
    410         self.write(STOP)

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save_tuple(self, obj)
    750         for element in obj:
--> 751             save(element)
    752 

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py in save_function(self, obj, name)
    377             if klass is None or klass is not obj:
--> 378                 self.save_function_tuple(obj)
    379                 return

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py in save_function_tuple(self, func)
    528         save(func.__module__)
--> 529         save(closure_values)
    530         write(pickle.TUPLE)

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save_list(self, obj)
    780         self.memoize(obj)
--> 781         self._batch_appends(obj)
    782 

/data/anaconda/envs/py36/lib/python3.6/pickle.py in _batch_appends(self, items)
    807             elif n:
--> 808                 save(tmp[0])
    809                 write(APPEND)

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py in save_function(self, obj, name)
    371                 or themodule is None):
--> 372             self.save_function_tuple(obj)
    373             return

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py in save_function_tuple(self, func)
    524         # save the rest of the func data needed by _fill_function
--> 525         save(f_globals)
    526         save(defaults)

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save_dict(self, obj)
    820         self.memoize(obj)
--> 821         self._batch_setitems(obj.items())
    822 

/data/anaconda/envs/py36/lib/python3.6/pickle.py in _batch_setitems(self, items)
    846                     save(k)
--> 847                     save(v)
    848                 write(SETITEMS)

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py in save_function(self, obj, name)
    371                 or themodule is None):
--> 372             self.save_function_tuple(obj)
    373             return

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py in save_function_tuple(self, func)
    524         # save the rest of the func data needed by _fill_function
--> 525         save(f_globals)
    526         save(defaults)

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save_dict(self, obj)
    820         self.memoize(obj)
--> 821         self._batch_setitems(obj.items())
    822 

/data/anaconda/envs/py36/lib/python3.6/pickle.py in _batch_setitems(self, items)
    846                     save(k)
--> 847                     save(v)
    848                 write(SETITEMS)

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    520         # Save the reduce() output and finally memoize the object
--> 521         self.save_reduce(obj=obj, *rv)
    522 

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    803         if state is not None:
--> 804             save(state)
    805             write(pickle.BUILD)

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save_dict(self, obj)
    820         self.memoize(obj)
--> 821         self._batch_setitems(obj.items())
    822 

/data/anaconda/envs/py36/lib/python3.6/pickle.py in _batch_setitems(self, items)
    846                     save(k)
--> 847                     save(v)
    848                 write(SETITEMS)

/data/anaconda/envs/py36/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    495             if reduce is not None:
--> 496                 rv = reduce(self.proto)
    497             else:

TypeError: can't pickle _thread.lock objects

During handling of the above exception, another exception occurred:

PicklingError                             Traceback (most recent call last)
<ipython-input-18-f997003aef22> in <module>
      8 # Parallelize feature engineering
      9 r = sc.parallelize(partitions, numSlices=N_PARTITIONS).\
---> 10     map(lambda x: partition_to_feature_matrix(x, feature_defs,
     11                                               'MS-31_labels.csv')).collect()
     12 sc.stop()

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/rdd.py in collect(self)
    832         """
    833         with SCCallSiteSync(self.context) as css:
--> 834             sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
    835         return list(_load_from_socket(sock_info, self._jrdd_deserializer))
    836 

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/rdd.py in _jrdd(self)
   2490 
   2491         wrapped_func = _wrap_function(self.ctx, self.func, self._prev_jrdd_deserializer,
-> 2492                                       self._jrdd_deserializer, profiler)
   2493         python_rdd = self.ctx._jvm.PythonRDD(self._prev_jrdd.rdd(), wrapped_func,
   2494                                              self.preservesPartitioning)

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/rdd.py in _wrap_function(sc, func, deserializer, serializer, profiler)
   2423     assert serializer, "serializer should not be empty"
   2424     command = (func, profiler, deserializer, serializer)
-> 2425     pickled_command, broadcast_vars, env, includes = _prepare_for_python_RDD(sc, command)
   2426     return sc._jvm.PythonFunction(bytearray(pickled_command), env, includes, sc.pythonExec,
   2427                                   sc.pythonVer, broadcast_vars, sc._javaAccumulator)

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/rdd.py in _prepare_for_python_RDD(sc, command)
   2409     # the serialized command will be compressed by broadcast
   2410     ser = CloudPickleSerializer()
-> 2411     pickled_command = ser.dumps(command)
   2412     if len(pickled_command) > (1 << 20):  # 1M
   2413         # The broadcast will have same life cycle as created PythonRDD

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/serializers.py in dumps(self, obj)
    573 
    574     def dumps(self, obj):
--> 575         return cloudpickle.dumps(obj, 2)
    576 
    577 

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py in dumps(obj, protocol)
    916 
    917     cp = CloudPickler(file,protocol)
--> 918     cp.dump(obj)
    919 
    920     return file.getvalue()

/usr/hdp/3.0.1.0-187/spark2/python/lib/pyspark.zip/pyspark/cloudpickle.py in dump(self, obj)
    247                 msg = "Could not serialize object: %s: %s" % (e.__class__.__name__, emsg)
    248             print_exec(sys.stderr)
--> 249             raise pickle.PicklingError(msg)
    250 
    251 

PicklingError: Could not serialize object: TypeError: can't pickle _thread.lock objects
```
my project is from the github: https://github.com/Featuretools/predict-customer-churn
I just modified the s3 to the hdfs.

when I run the "2._Prediction_Engineering" on spark to generate the cutoff time and labels I alose face the same problem.

I alse search my problem on the stackoverflow, but it can't solve my problems.

**Comment by kmax12** [comment]
Hi! it's not clear where the issue with Featuretools is here, so I am going to close this for now. 

I recommend you can post it the repo (https://github.com/Featuretools/predict-customer-churn) and we can take a look at there
